### ISSUE TITLE
v0.1.0 throws "panic: module already registered: k6/x/redis"

### ISSUE THREAD

**Issue by vincentdaniel** [grafana/xk6-redis#10]
Since [the extension was made importable by k6 in v0.1.0](https://github.com/grafana/xk6-redis/commit/fcfd70cb97feed607f749d7f94021dc462e7ee7f), we are getting an error when running k6 with xk6-redis:
```
goroutine 1 [running]:
go.k6.io/k6/js/modules.Register({0x102f1454e, 0xa}, {0x10325e5c0?, 0x103e44830})
	go.k6.io/k6@v0.38.2/js/modules/modules.go:54 +0x18c
github.com/grafana/xk6-redis.init.0()
	github.com/grafana/xk6-redis@v0.1.0/register.go:10 +0x3c
```

*Steps to reproduce*

script.js:
```javascript
import redis from 'k6/x/redis';

export const redisClient = new redis.Client({
    addrs: new Array("localhost:6379"),
    password: 'redis',
    db: 0,
  });

export default function () {

}
```

script.sh
```bash
go install go.k6.io/xk6/cmd/xk6@latest
xk6 build --with github.com/grafana/xk6-redis
./k6 run script.js
```

`./script.sh`

*Workaround*

Use previous version : `xk6 build --with github.com/grafana/xk6-redis@100588d`

*Comment*

I guess the warning was there for a reason 😄 
`This extension is going under heavy changes and is about to make it to k6's core. USE AT YOUR OWN RISK!`

But I wanted to still raise the issue in case there is a better workaround or a way to fix the current version to make it work with current readme 😉

**Comment by mstoykov** [comment]
Thanks for reporting this :bow. This was fixed with #11, but we forgot to mention it here.
