### ISSUE TITLE
Cannot run in cluster mode

### ISSUE THREAD

**Issue by 100kimch** [grafana/xk6-redis#15]
Hi, I'm trying to use this cool stuff, but it doesn't seem to be worked on my system.

I'm using Azure Cache for Redis which has a single endpoint to do load-balance among shard hosts.

I set up with example test scripts, ran `k6 run demo.js`, and it has these errors:

```text
ERRO[0000] Uncaught (in promise) MOVED 7220 172.23.16.132:13004  executor=shared-iterations scenario=usingRedisData
ERRO[0000] Uncaught (in promise) MOVED 7220 172.23.16.132:13004  executor=shared-iterations scenario=usingRedisData
ERRO[0000] Uncaught (in promise) MOVED 9988 172.23.16.132:13003  executor=shared-iterations scenario=redisPerformance
ERRO[0000] Uncaught (in promise) MOVED 7220 172.23.16.132:13004  executor=shared-iterations scenario=usingRedisData
```

It doesn't seem to recognize the cluster mode. Is there any solution to work out?

**Comment by oleiade** [comment]
Hi @100kimch 👋🏻 

Another user recently reported limitations with using the cluster mode in the latest version of the extension: https://github.com/grafana/k6/issues/3031

Could it be related? If so, we have offered some temporary workarounds there. Could you try them and let us know how that goes for you? 🙇🏻 

We're currently looking into updating the go-redis dependency to a version offering better clustering support. No ETA yet.

**Comment by oleiade** [comment]
ref https://github.com/grafana/k6/issues/3081

**Comment by 100kimch** [comment]
Hi @oleiade!

I'm afraid it's not related to that issues.

- I'm using Redis 6.0 with cluster mode. It means it's not the newest 7.0 issue. The `MOVED` response has occurred because a master doesn't have the requested key when a key-value exists on other master node.
- There should have a logic for the cluster mode. Otherwise, I can never use this feature :(

Regards,
Jaycol Kim

**Comment by oleiade** [comment]
Hey @100kimch 👋🏻 

Thanks for the clarification 🙇🏻 

I would need more info from you to track down the issue if you don't mind. To ensure we are as exhaustive as possible, could you provide us with an anonymized script example demonstrating the problem on your side, your expected output, and what output you receive?

Under the hood, we rely on the go-redis library, which advertises support for cluster mode, and we explicitly adapted our usage to make it available. However, as you can see, the "experimental" status is somewhat justified 😄. We will look further into stabilizing support for the cluster mode indeed, but no ETA yet.
