### ISSUE TITLE
i fail to get the redis values,help plz~~

### ISSUE THREAD

**Issue by kingxyt06** [grafana/xk6-redis#28]
![image](https://github.com/grafana/xk6-redis/assets/35811108/edc02065-d481-491e-9385-a595968711ca)
![image](https://github.com/grafana/xk6-redis/assets/35811108/f9c53883-a556-4ecf-9f86-bc659c08532c)

as like the pic，why client.get()  return {} , help me plzzzzzz~~  
the redis already set , but get return {}...

i also try the sample like:
client.set('res','123')
client.get('res')
but also return {}

**Comment by codebien** [comment]
Hey @kingxyt06,
the `client.get` method returns a Promise. Check [the documentation](https://k6.io/docs/javascript-api/k6-experimental/redis/client/client-get) to see how to use it.

Feel free to reopen if you still don't get the value.
