### ISSUE TITLE
maxConnAge description is misleading

### ISSUE THREAD

**Issue by mkosta** [grafana/xk6-redis#32]
maxConnAge description says that this parameter manages idle connections, which is misleading. if there is one conection open and is fully and constantly utilized by redis client, socket will be still closed after connection life time reaches this maxage vaue despite connection status. so it has nothing to do with idleness, but is simply maxlifetime of connection. readin the doc i figured it will close idle connections after say 10 secs, but what i got was sockets are being closed and opened every 10 secs. and once you set it as 0, it is handled like persistent socket and same load is going through one socket for hours.
we should just remove "idle" from the doc) thanks

/**
     * The maximum amount of time, in milliseconds, a connection can stay idle in the pool before being closed.
     *
     * This can help in cycling connections and preventing stale connections.
     */
    maxConnAge?: number;

**Comment by joanlopez** [comment]
Hi @mkosta,

Yeah, I think you're right! [`maxConnAge` is used as `ConnMaxLifetime`](https://github.com/grafana/xk6-redis/blob/b91517dcd4bbf105c52ae71eb2ea9983f14996c6/redis/options.go#L335), and from the library docs:

```
// ConnMaxLifetime is the maximum amount of time a connection may be reused.
//
// Expired connections may be closed lazily before reuse.
// If <= 0, connections are not closed due to a connection's age.
//
// Default is to not close idle connections.
```
which isn't the same as `ConnMaxIdleTime`, which in `xk6-redis` [is configured with: `idleTimeout`](https://github.com/grafana/xk6-redis/blob/b91517dcd4bbf105c52ae71eb2ea9983f14996c6/redis/options.go#L337).

I'll open a PR in [k6-docs](https://github.com/grafana/k6-docs) to fix it.

Thanks for reporting it! 🙇🏻

**Comment by mkosta** [comment]
@joanlopez thank you!
